Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.165.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'SetSuffixOptionsSUFFIXCOLFIELD' data form
''' </summary>
Partial Public Class [SetSuffixOptionsSUFFIXCOLFIELDUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _suffixcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _isacademic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _isfamilial As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _isprofessional As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _isreligious As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public Sub New()
        MyBase.New()

        _suffixcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _isacademic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _isfamilial = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _isprofessional = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _isreligious = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

        '
        '_suffixcodeid
        '
        _suffixcodeid.Name = "SUFFIXCODEID"
        _suffixcodeid.Caption = "Suffix"
        _suffixcodeid.CodeTableName = "SUFFIXCODE"
        _suffixcodeid.IncludeInactive = True
        Me.Fields.Add(_suffixcodeid)
        '
        '_isacademic
        '
        _isacademic.Name = "ISACADEMIC"
        _isacademic.Caption = "Is Suffix Academic? (PhD, MD, DO, DDS)"
        Me.Fields.Add(_isacademic)
        '
        '_isfamilial
        '
        _isfamilial.Name = "ISFAMILIAL"
        _isfamilial.Caption = "Is Suffix Familial? (Jr, Sr, III)"
        Me.Fields.Add(_isfamilial)
        '
        '_isprofessional
        '
        _isprofessional.Name = "ISPROFESSIONAL"
        _isprofessional.Caption = "Is Suffix Professional? (CPA, MBA)"
        Me.Fields.Add(_isprofessional)
        '
        '_isreligious
        '
        _isreligious.Name = "ISRELIGIOUS"
        _isreligious.Caption = "Is Suffix Religious? (RSM)"
        Me.Fields.Add(_isreligious)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Suffix
    ''' </summary>
    <System.ComponentModel.Description("Suffix")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public ReadOnly Property [SUFFIXCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _suffixcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Is Suffix Academic? (PhD, MD, DO, DDS)
    ''' </summary>
    <System.ComponentModel.Description("Is Suffix Academic? (PhD, MD, DO, DDS)")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public ReadOnly Property [ISACADEMIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isacademic
        End Get
    End Property
    
    ''' <summary>
    ''' Is Suffix Familial? (Jr, Sr, III)
    ''' </summary>
    <System.ComponentModel.Description("Is Suffix Familial? (Jr, Sr, III)")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public ReadOnly Property [ISFAMILIAL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isfamilial
        End Get
    End Property
    
    ''' <summary>
    ''' Is Suffix Professional? (CPA, MBA)
    ''' </summary>
    <System.ComponentModel.Description("Is Suffix Professional? (CPA, MBA)")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public ReadOnly Property [ISPROFESSIONAL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isprofessional
        End Get
    End Property
    
    ''' <summary>
    ''' Is Suffix Religious? (RSM)
    ''' </summary>
    <System.ComponentModel.Description("Is Suffix Religious? (RSM)")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public ReadOnly Property [ISRELIGIOUS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isreligious
        End Get
    End Property
    
End Class
