Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.165.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Set Title Options' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "c3475edf-4500-4562-a6e8-5916a6467f87", "5a8b26e0-37b8-4fea-a8d0-7081ef226eed", "")>
Partial Public Class [SetTitleOptionsUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _titlecolfield As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SetTitleOptionsTITLECOLFIELDUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public Sub New()
        MyBase.New()

        _titlecolfield = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SetTitleOptionsTITLECOLFIELDUIModel)

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New System.Guid("c3475edf-4500-4562-a6e8-5916a6467f87")
        MyBase.DataFormInstanceId = New System.Guid("5a8b26e0-37b8-4fea-a8d0-7081ef226eed")
        MyBase.RecordType = ""
        MyBase.FORMHEADER.Value = "Set Title Options"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.nameformats/SetTitleOptions.html"

        '
        '_titlecolfield
        '
        _titlecolfield.Name = "TITLECOLFIELD"
        _titlecolfield.Caption = "Title Collection"
        _titlecolfield.EnablePaging = True
        _titlecolfield.ItemsPerPage = 100
        Me.Fields.Add(_titlecolfield)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Title Collection
    ''' </summary>
    <System.ComponentModel.Description("Title Collection")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")> _
    Public ReadOnly Property [TITLECOLFIELD]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of SetTitleOptionsTITLECOLFIELDUIModel)
        Get
            Return _titlecolfield
        End Get
    End Property
    
End Class
